server_announce = false
enable_damage = true
creative_mode = false
menu_last_game = devtest
mainmenu_last_selected_world = 1
maintab_LAST = about
security_info_security_score = 0/100 (Insecure)
security_info_tls_version = None
security_info_server_fingerprint = 
security_info_connected_since = 0
security_info_server_port = 54301
security_info_server_address = 
security_info_state = Insecure
security_info_session_id = 
security_info_key_exchange = None
security_info_protocol_version = 51
security_info_encryption = None
security_info_authentication = None
security_info_cert_status = Not Verified
security_info_replay_protection = No
security_info_cipher_suite = None
security_info_forward_secrecy = No
